<?php

namespace ContainerSfkSBI8;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GTWkntZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gTWkntZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gTWkntZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'serviceAccount' => ['privates', '.errored..service_locator.gTWkntZ.App\\Entity\\ServiceAccount', NULL, 'Cannot autowire service ".service_locator.gTWkntZ": it needs an instance of "App\\Entity\\ServiceAccount" but this type has been excluded in "config/services.yaml".'],
        ], [
            'serviceAccount' => 'App\\Entity\\ServiceAccount',
        ]);
    }
}
