<?php

namespace ContainerKemSBV2;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HhEvZkcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HhEvZkc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HhEvZkc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'activityRepository' => ['privates', 'App\\Repository\\ActivityRepository', 'getActivityRepositoryService', true],
            'categoryRepository' => ['privates', 'App\\Repository\\ActivityCategoryRepository', 'getActivityCategoryRepositoryService', true],
        ], [
            'activityRepository' => 'App\\Repository\\ActivityRepository',
            'categoryRepository' => 'App\\Repository\\ActivityCategoryRepository',
        ]);
    }
}
