<?php

namespace ContainerChVEwbY;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EQ0Vet0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eQ0Vet0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eQ0Vet0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'serviceAccount' => ['privates', '.errored..service_locator.eQ0Vet0.App\\Entity\\ServiceAccount', NULL, 'Cannot autowire service ".service_locator.eQ0Vet0": it needs an instance of "App\\Entity\\ServiceAccount" but this type has been excluded in "config/services.yaml".'],
            'serviceAccountRepository' => ['privates', 'App\\Repository\\ServiceAccountRepository', 'getServiceAccountRepositoryService', true],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'serviceAccount' => 'App\\Entity\\ServiceAccount',
            'serviceAccountRepository' => 'App\\Repository\\ServiceAccountRepository',
            'passwordHasher' => '?',
        ]);
    }
}
