<?php

namespace ContainerIYf86tn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9_2i6tjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9.2i6tj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9.2i6tj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'planning' => ['privates', '.errored..service_locator.9.2i6tj.App\\Entity\\Planning', NULL, 'Cannot autowire service ".service_locator.9.2i6tj": it needs an instance of "App\\Entity\\Planning" but this type has been excluded in "config/services.yaml".'],
            'planningRepository' => ['privates', 'App\\Repository\\PlanningRepository', 'getPlanningRepositoryService', true],
        ], [
            'planning' => 'App\\Entity\\Planning',
            'planningRepository' => 'App\\Repository\\PlanningRepository',
        ]);
    }
}
