<?php

namespace ContainerIYf86tn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SMJi2XnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SMJi2Xn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SMJi2Xn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'serviceAccountRepository' => ['privates', 'App\\Repository\\ServiceAccountRepository', 'getServiceAccountRepositoryService', true],
        ], [
            'serviceAccountRepository' => 'App\\Repository\\ServiceAccountRepository',
        ]);
    }
}
