<?php

namespace ContainerIYf86tn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceAccount2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.eQ0Vet0.App\Entity\ServiceAccount' shared service.
     *
     * @return \App\Entity\ServiceAccount
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.eQ0Vet0": it needs an instance of "App\\Entity\\ServiceAccount" but this type has been excluded in "config/services.yaml".');
    }
}
