<?php

namespace ContainerLkMVEJj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceAccountService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.YOMzJgl.App\Entity\ServiceAccount' shared service.
     *
     * @return \App\Entity\ServiceAccount
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.YOMzJgl": it needs an instance of "App\\Entity\\ServiceAccount" but this type has been excluded in "config/services.yaml".');
    }
}
