<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDtiy3xZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDtiy3xZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDtiy3xZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDtiy3xZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDtiy3xZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Dtiy3xZ',
    'container.build_id' => '830d6b1a',
    'container.build_time' => 1747388482,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDtiy3xZ');
