<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLkMVEJj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLkMVEJj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLkMVEJj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLkMVEJj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLkMVEJj\App_KernelDevDebugContainer([
    'container.build_hash' => 'LkMVEJj',
    'container.build_id' => 'b05948ca',
    'container.build_time' => 1747301239,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLkMVEJj');
