<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_core-js_modules_es_array_concat_js-node_modules_core-js_modules_es_array-b1522a.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/app.css',
            ],
        ],
    ],
],

]];
