<?php

namespace ContainerDtiy3xZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JI7Tj5WService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jI7Tj5W' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jI7Tj5W'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'serviceAccountRepository' => ['privates', 'App\\Repository\\ServiceAccountRepository', 'getServiceAccountRepositoryService', true],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'serviceAccountRepository' => 'App\\Repository\\ServiceAccountRepository',
            'passwordHasher' => '?',
        ]);
    }
}
