<?php

namespace ContainerDtiy3xZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KIhFha6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kIhFha6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kIhFha6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'planning' => ['privates', '.errored..service_locator.kIhFha6.App\\Entity\\Planning', NULL, 'Cannot autowire service ".service_locator.kIhFha6": it needs an instance of "App\\Entity\\Planning" but this type has been excluded in "config/services.yaml".'],
        ], [
            'planning' => 'App\\Entity\\Planning',
        ]);
    }
}
